TrainingArguments:
    evaluation_strategy: no
    save_strategy: epoch
    num_train_epochs: 3
    num_update_step_per_epoch: 8
    batch_size: 8
    push_to_hub: False
    num_warmup_steps: 0
    logging_steps: 10
    eval_steps:
    save_steps:
    gradient_accumulation_steps: