artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Huynguyen610/Squad-Dataset/raw/main/Squad-Dataset.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "validation"]


data_transformation:
  root_dir: artifacts/data_transformation
  train_data_path: artifacts/data_ingestion/train
  valid_data_path: artifacts/data_ingestion/validation
  tokenizer_name: bert-base-cased


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train_dataset
  valid_data_path: artifacts/data_transformation/validation_dataset
  model_checkpoint: bert-base-cased


model_evaluation:
  root_dir: artifacts/model_evaluation
  raw_valid_data_path: artifacts/data_ingestion/validation
  train_data_path: artifacts/data_transformation/train_dataset
  valid_data_path: artifacts/data_transformation/validation_dataset
  model_path: artifacts/model_trainer
  tokenizer_path: artifacts/model_trainer/tokenizer_config.json
  metric_file_name: artifacts/model_evaluation/metrics.csv

