#name: Question-Answering Application

#on:
 # push:
  #  branches:
   # - main
  #pull_request:
  #  branches:
  #  - main

#jobs:
 # build:

  #  runs-on: ubuntu-latest

   # steps:
    #- name: Checkout
     # uses: actions/checkout@v2


   # - name: Deploy to Heroku
    #  uses: gonuit/heroku-docker-deploy@v1.3.3 # GitHub action name (leave it as it is).
     # with:
      #  email: huy61098@gmail.com
       # heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        #heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        #dockerfile_directory: ./
        #dockerfile_name: Dockerfile
        #docker_options: "--no-cache"
        #process_type: web
